<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@// Source: riak.proto
//   Date: 2015-01-16 03:40:25


namespace Riak\Client\ProtoBuf\DtFetchResp {

            class DataType extends \DrSlump\Protobuf\Enum
            {
                const COUNTER = 1;
                const SET = 2;
                const MAP = 3;
            }
}
