<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@// Source: riak.proto
//   Date: 2015-01-16 03:40:25


namespace Riak\Client\ProtoBuf\MapField {

            class MapFieldType extends \DrSlump\Protobuf\Enum
            {
                const COUNTER = 1;
                const SET = 2;
                const REGISTER = 3;
                const FLAG = 4;
                const MAP = 5;
            }
}
