<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : riak.proto
 */


namespace Riak\Client\ProtoBuf\MapField;

/**
 * Protobuf enum : MapField.MapFieldType
 */
class MapFieldType extends \Protobuf\Enum
{

    /**
     * COUNTER = 1
     */
    const COUNTER_VALUE = 1;

    /**
     * SET = 2
     */
    const SET_VALUE = 2;

    /**
     * REGISTER = 3
     */
    const REGISTER_VALUE = 3;

    /**
     * FLAG = 4
     */
    const FLAG_VALUE = 4;

    /**
     * MAP = 5
     */
    const MAP_VALUE = 5;

    /**
     * @var \Riak\Client\ProtoBuf\MapField\MapFieldType
     */
    protected static $COUNTER = null;

    /**
     * @var \Riak\Client\ProtoBuf\MapField\MapFieldType
     */
    protected static $SET = null;

    /**
     * @var \Riak\Client\ProtoBuf\MapField\MapFieldType
     */
    protected static $REGISTER = null;

    /**
     * @var \Riak\Client\ProtoBuf\MapField\MapFieldType
     */
    protected static $FLAG = null;

    /**
     * @var \Riak\Client\ProtoBuf\MapField\MapFieldType
     */
    protected static $MAP = null;

    /**
     * @return \Riak\Client\ProtoBuf\MapField\MapFieldType
     */
    public static function COUNTER()
    {
        if (self::$COUNTER !== null) {
            return self::$COUNTER;
        }

        return self::$COUNTER = new self('COUNTER', self::COUNTER_VALUE);
    }

    /**
     * @return \Riak\Client\ProtoBuf\MapField\MapFieldType
     */
    public static function SET()
    {
        if (self::$SET !== null) {
            return self::$SET;
        }

        return self::$SET = new self('SET', self::SET_VALUE);
    }

    /**
     * @return \Riak\Client\ProtoBuf\MapField\MapFieldType
     */
    public static function REGISTER()
    {
        if (self::$REGISTER !== null) {
            return self::$REGISTER;
        }

        return self::$REGISTER = new self('REGISTER', self::REGISTER_VALUE);
    }

    /**
     * @return \Riak\Client\ProtoBuf\MapField\MapFieldType
     */
    public static function FLAG()
    {
        if (self::$FLAG !== null) {
            return self::$FLAG;
        }

        return self::$FLAG = new self('FLAG', self::FLAG_VALUE);
    }

    /**
     * @return \Riak\Client\ProtoBuf\MapField\MapFieldType
     */
    public static function MAP()
    {
        if (self::$MAP !== null) {
            return self::$MAP;
        }

        return self::$MAP = new self('MAP', self::MAP_VALUE);
    }

    /**
     * @param int $value
     * @return \Riak\Client\ProtoBuf\MapField\MapFieldType
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 1: return self::COUNTER();
            case 2: return self::SET();
            case 3: return self::REGISTER();
            case 4: return self::FLAG();
            case 5: return self::MAP();
            default: return null;
        }
    }


}

