<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : riak.proto
 */


namespace Riak\Client\ProtoBuf\RpbBucketProps;

/**
 * Protobuf enum : RpbBucketProps.RpbReplMode
 */
class RpbReplMode extends \Protobuf\Enum
{

    /**
     * FALSE = 0
     */
    const FALSE_VALUE = 0;

    /**
     * REALTIME = 1
     */
    const REALTIME_VALUE = 1;

    /**
     * FULLSYNC = 2
     */
    const FULLSYNC_VALUE = 2;

    /**
     * TRUE = 3
     */
    const TRUE_VALUE = 3;

    /**
     * @var \Riak\Client\ProtoBuf\RpbBucketProps\RpbReplMode
     */
    protected static $FALSE = null;

    /**
     * @var \Riak\Client\ProtoBuf\RpbBucketProps\RpbReplMode
     */
    protected static $REALTIME = null;

    /**
     * @var \Riak\Client\ProtoBuf\RpbBucketProps\RpbReplMode
     */
    protected static $FULLSYNC = null;

    /**
     * @var \Riak\Client\ProtoBuf\RpbBucketProps\RpbReplMode
     */
    protected static $TRUE = null;

    /**
     * @return \Riak\Client\ProtoBuf\RpbBucketProps\RpbReplMode
     */
    public static function FALSE()
    {
        if (self::$FALSE !== null) {
            return self::$FALSE;
        }

        return self::$FALSE = new self('FALSE', self::FALSE_VALUE);
    }

    /**
     * @return \Riak\Client\ProtoBuf\RpbBucketProps\RpbReplMode
     */
    public static function REALTIME()
    {
        if (self::$REALTIME !== null) {
            return self::$REALTIME;
        }

        return self::$REALTIME = new self('REALTIME', self::REALTIME_VALUE);
    }

    /**
     * @return \Riak\Client\ProtoBuf\RpbBucketProps\RpbReplMode
     */
    public static function FULLSYNC()
    {
        if (self::$FULLSYNC !== null) {
            return self::$FULLSYNC;
        }

        return self::$FULLSYNC = new self('FULLSYNC', self::FULLSYNC_VALUE);
    }

    /**
     * @return \Riak\Client\ProtoBuf\RpbBucketProps\RpbReplMode
     */
    public static function TRUE()
    {
        if (self::$TRUE !== null) {
            return self::$TRUE;
        }

        return self::$TRUE = new self('TRUE', self::TRUE_VALUE);
    }

    /**
     * @param int $value
     * @return \Riak\Client\ProtoBuf\RpbBucketProps\RpbReplMode
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::FALSE();
            case 1: return self::REALTIME();
            case 2: return self::FULLSYNC();
            case 3: return self::TRUE();
            default: return null;
        }
    }


}

