<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : riak.proto
 */


namespace Riak\Client\ProtoBuf;

/**
 * Protobuf message : MapOp
 */
class MapOp extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * removes repeated message = 1
     *
     * @var \Protobuf\Collection<\Riak\Client\ProtoBuf\MapField>
     */
    protected $removes = null;

    /**
     * updates repeated message = 2
     *
     * @var \Protobuf\Collection<\Riak\Client\ProtoBuf\MapUpdate>
     */
    protected $updates = null;

    /**
     * Check if 'removes' has a value
     *
     * @return bool
     */
    public function hasRemovesList()
    {
        return $this->removes !== null;
    }

    /**
     * Get 'removes' value
     *
     * @return \Protobuf\Collection<\Riak\Client\ProtoBuf\MapField>
     */
    public function getRemovesList()
    {
        return $this->removes;
    }

    /**
     * Set 'removes' value
     *
     * @param \Protobuf\Collection<\Riak\Client\ProtoBuf\MapField> $value
     */
    public function setRemovesList(\Protobuf\Collection $value = null)
    {
        $this->removes = $value;
    }

    /**
     * Add a new element to 'removes'
     *
     * @param \Riak\Client\ProtoBuf\MapField $value
     */
    public function addRemoves(\Riak\Client\ProtoBuf\MapField $value)
    {
        if ($this->removes === null) {
            $this->removes = new \Protobuf\MessageCollection();
        }

        $this->removes->add($value);
    }

    /**
     * Check if 'updates' has a value
     *
     * @return bool
     */
    public function hasUpdatesList()
    {
        return $this->updates !== null;
    }

    /**
     * Get 'updates' value
     *
     * @return \Protobuf\Collection<\Riak\Client\ProtoBuf\MapUpdate>
     */
    public function getUpdatesList()
    {
        return $this->updates;
    }

    /**
     * Set 'updates' value
     *
     * @param \Protobuf\Collection<\Riak\Client\ProtoBuf\MapUpdate> $value
     */
    public function setUpdatesList(\Protobuf\Collection $value = null)
    {
        $this->updates = $value;
    }

    /**
     * Add a new element to 'updates'
     *
     * @param \Riak\Client\ProtoBuf\MapUpdate $value
     */
    public function addUpdates(\Riak\Client\ProtoBuf\MapUpdate $value)
    {
        if ($this->updates === null) {
            $this->updates = new \Protobuf\MessageCollection();
        }

        $this->updates->add($value);
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'removes' => [],
            'updates' => []
        ], $values);

        foreach ($values['removes'] as $item) {
            $message->addRemoves($item);
        }

        foreach ($values['updates'] as $item) {
            $message->addUpdates($item);
        }

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'MapOp',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'removes',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED(),
                    'type_name' => '.MapField'
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'updates',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_MESSAGE(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REPEATED(),
                    'type_name' => '.MapUpdate'
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->removes !== null) {
            foreach ($this->removes as $val) {
                $writer->writeVarint($stream, 10);
                $writer->writeVarint($stream, $val->serializedSize($sizeContext));
                $val->writeTo($context);
            }
        }

        if ($this->updates !== null) {
            foreach ($this->updates as $val) {
                $writer->writeVarint($stream, 18);
                $writer->writeVarint($stream, $val->serializedSize($sizeContext));
                $val->writeTo($context);
            }
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \Riak\Client\ProtoBuf\MapField();

                if ($this->removes === null) {
                    $this->removes = new \Protobuf\MessageCollection();
                }

                $this->removes->add($innerMessage);

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 11);

                $innerSize    = $reader->readVarint($stream);
                $innerMessage = new \Riak\Client\ProtoBuf\MapUpdate();

                if ($this->updates === null) {
                    $this->updates = new \Protobuf\MessageCollection();
                }

                $this->updates->add($innerMessage);

                $context->setLength($innerSize);
                $innerMessage->readFrom($context);
                $context->setLength($length);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->removes !== null) {
            foreach ($this->removes as $val) {
                $innerSize = $val->serializedSize($context);

                $size += 1;
                $size += $innerSize;
                $size += $calculator->computeVarintSize($innerSize);
            }
        }

        if ($this->updates !== null) {
            foreach ($this->updates as $val) {
                $innerSize = $val->serializedSize($context);

                $size += 1;
                $size += $innerSize;
                $size += $calculator->computeVarintSize($innerSize);
            }
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->removes = null;
        $this->updates = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \Riak\Client\ProtoBuf\MapOp) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->removes = ($message->removes !== null) ? $message->removes : $this->removes;
        $this->updates = ($message->updates !== null) ? $message->updates : $this->updates;
    }


}

