<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : riak.proto
 */


namespace Riak\Client\ProtoBuf;

/**
 * Protobuf message : RpbCounterGetReq
 */
class RpbCounterGetReq extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * bucket required bytes = 1
     *
     * @var \Protobuf\Stream
     */
    protected $bucket = null;

    /**
     * key required bytes = 2
     *
     * @var \Protobuf\Stream
     */
    protected $key = null;

    /**
     * r optional uint32 = 3
     *
     * @var int
     */
    protected $r = null;

    /**
     * pr optional uint32 = 4
     *
     * @var int
     */
    protected $pr = null;

    /**
     * basic_quorum optional bool = 5
     *
     * @var bool
     */
    protected $basic_quorum = null;

    /**
     * notfound_ok optional bool = 6
     *
     * @var bool
     */
    protected $notfound_ok = null;

    /**
     * Check if 'bucket' has a value
     *
     * @return bool
     */
    public function hasBucket()
    {
        return $this->bucket !== null;
    }

    /**
     * Get 'bucket' value
     *
     * @return \Protobuf\Stream
     */
    public function getBucket()
    {
        return $this->bucket;
    }

    /**
     * Set 'bucket' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setBucket($value)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->bucket = $value;
    }

    /**
     * Check if 'key' has a value
     *
     * @return bool
     */
    public function hasKey()
    {
        return $this->key !== null;
    }

    /**
     * Get 'key' value
     *
     * @return \Protobuf\Stream
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Set 'key' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setKey($value)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->key = $value;
    }

    /**
     * Check if 'r' has a value
     *
     * @return bool
     */
    public function hasR()
    {
        return $this->r !== null;
    }

    /**
     * Get 'r' value
     *
     * @return int
     */
    public function getR()
    {
        return $this->r;
    }

    /**
     * Set 'r' value
     *
     * @param int $value
     */
    public function setR($value = null)
    {
        $this->r = $value;
    }

    /**
     * Check if 'pr' has a value
     *
     * @return bool
     */
    public function hasPr()
    {
        return $this->pr !== null;
    }

    /**
     * Get 'pr' value
     *
     * @return int
     */
    public function getPr()
    {
        return $this->pr;
    }

    /**
     * Set 'pr' value
     *
     * @param int $value
     */
    public function setPr($value = null)
    {
        $this->pr = $value;
    }

    /**
     * Check if 'basic_quorum' has a value
     *
     * @return bool
     */
    public function hasBasicQuorum()
    {
        return $this->basic_quorum !== null;
    }

    /**
     * Get 'basic_quorum' value
     *
     * @return bool
     */
    public function getBasicQuorum()
    {
        return $this->basic_quorum;
    }

    /**
     * Set 'basic_quorum' value
     *
     * @param bool $value
     */
    public function setBasicQuorum($value = null)
    {
        $this->basic_quorum = $value;
    }

    /**
     * Check if 'notfound_ok' has a value
     *
     * @return bool
     */
    public function hasNotfoundOk()
    {
        return $this->notfound_ok !== null;
    }

    /**
     * Get 'notfound_ok' value
     *
     * @return bool
     */
    public function getNotfoundOk()
    {
        return $this->notfound_ok;
    }

    /**
     * Set 'notfound_ok' value
     *
     * @param bool $value
     */
    public function setNotfoundOk($value = null)
    {
        $this->notfound_ok = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['bucket'])) {
            throw new \InvalidArgumentException('Field "bucket" (tag 1) is required but has no value.');
        }

        if ( ! isset($values['key'])) {
            throw new \InvalidArgumentException('Field "key" (tag 2) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
            'r' => null,
            'pr' => null,
            'basic_quorum' => null,
            'notfound_ok' => null
        ], $values);

        $message->setBucket($values['bucket']);
        $message->setKey($values['key']);
        $message->setR($values['r']);
        $message->setPr($values['pr']);
        $message->setBasicQuorum($values['basic_quorum']);
        $message->setNotfoundOk($values['notfound_ok']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'RpbCounterGetReq',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'bucket',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'key',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'r',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'pr',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'basic_quorum',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 6,
                    'name' => 'notfound_ok',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->bucket === null) {
            throw new \UnexpectedValueException('Field "\\Riak\\Client\\ProtoBuf\\RpbCounterGetReq#bucket" (tag 1) is required but has no value.');
        }

        if ($this->key === null) {
            throw new \UnexpectedValueException('Field "\\Riak\\Client\\ProtoBuf\\RpbCounterGetReq#key" (tag 2) is required but has no value.');
        }

        if ($this->bucket !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeByteStream($stream, $this->bucket);
        }

        if ($this->key !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeByteStream($stream, $this->key);
        }

        if ($this->r !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->r);
        }

        if ($this->pr !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeVarint($stream, $this->pr);
        }

        if ($this->basic_quorum !== null) {
            $writer->writeVarint($stream, 40);
            $writer->writeBool($stream, $this->basic_quorum);
        }

        if ($this->notfound_ok !== null) {
            $writer->writeVarint($stream, 48);
            $writer->writeBool($stream, $this->notfound_ok);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->bucket = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->key = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->r = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->pr = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->basic_quorum = $reader->readBool($stream);

                continue;
            }

            if ($tag === 6) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->notfound_ok = $reader->readBool($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->bucket !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->bucket);
        }

        if ($this->key !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->key);
        }

        if ($this->r !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->r);
        }

        if ($this->pr !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->pr);
        }

        if ($this->basic_quorum !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->notfound_ok !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->bucket = null;
        $this->key = null;
        $this->r = null;
        $this->pr = null;
        $this->basic_quorum = null;
        $this->notfound_ok = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \Riak\Client\ProtoBuf\RpbCounterGetReq) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->bucket = ($message->bucket !== null) ? $message->bucket : $this->bucket;
        $this->key = ($message->key !== null) ? $message->key : $this->key;
        $this->r = ($message->r !== null) ? $message->r : $this->r;
        $this->pr = ($message->pr !== null) ? $message->pr : $this->pr;
        $this->basic_quorum = ($message->basic_quorum !== null) ? $message->basic_quorum : $this->basic_quorum;
        $this->notfound_ok = ($message->notfound_ok !== null) ? $message->notfound_ok : $this->notfound_ok;
    }


}

