<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@// Source: riak.proto
//   Date: 2015-01-16 03:40:25


namespace Riak\Client\ProtoBuf {

    class RpbGetClientIdResp extends \DrSlump\Protobuf\Message
    {
        /** @var \DrSlump\Protobuf\Descriptor */
        protected static $__descriptor;
        /** @var \Closure[] */
        protected static $__extensions = array();

        public static function descriptor()
        {
            $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, '.RpbGetClientIdResp');

            // required bytes client_id = 1
            $f = new \DrSlump\Protobuf\Field();
            $f->number = 1;
            $f->name   = "client_id";
            $f->rule   = \DrSlump\Protobuf\Protobuf::RULE_REQUIRED;
            $f->type   = \DrSlump\Protobuf\Protobuf::TYPE_BYTES;

            $descriptor->addField($f);

            foreach (self::$__extensions as $cb) {
                $descriptor->addField($cb(), true);
            }

            return $descriptor;
        }

        /**
         * Check if "client_id" has a value
         *
         * @return boolean
         */
        public function hasClientId()
        {
            return isset($this->client_id);
        }

        /**
         * Clear "client_id" value
         */
        public function clearClientId()
        {
            unset($this->client_id);
        }

        /**
         * Get "client_id" value
         * @return string                  *
         *
         */
        public function getClientId()
        {
            return $this->client_id;
        }

        /**
         * Set "client_id" value
         *
         * @param string $value
         */
        public function setClientId($value)
        {
            return $this->client_id = $value;
        }
    }
}
