<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : riak.proto
 */


namespace Riak\Client\ProtoBuf;

/**
 * Protobuf message : RpbGetReq
 */
class RpbGetReq extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * bucket required bytes = 1
     *
     * @var \Protobuf\Stream
     */
    protected $bucket = null;

    /**
     * key required bytes = 2
     *
     * @var \Protobuf\Stream
     */
    protected $key = null;

    /**
     * r optional uint32 = 3
     *
     * @var int
     */
    protected $r = null;

    /**
     * pr optional uint32 = 4
     *
     * @var int
     */
    protected $pr = null;

    /**
     * basic_quorum optional bool = 5
     *
     * @var bool
     */
    protected $basic_quorum = null;

    /**
     * notfound_ok optional bool = 6
     *
     * @var bool
     */
    protected $notfound_ok = null;

    /**
     * if_modified optional bytes = 7
     *
     * @var \Protobuf\Stream
     */
    protected $if_modified = null;

    /**
     * head optional bool = 8
     *
     * @var bool
     */
    protected $head = null;

    /**
     * deletedvclock optional bool = 9
     *
     * @var bool
     */
    protected $deletedvclock = null;

    /**
     * timeout optional uint32 = 10
     *
     * @var int
     */
    protected $timeout = null;

    /**
     * sloppy_quorum optional bool = 11
     *
     * @var bool
     */
    protected $sloppy_quorum = null;

    /**
     * n_val optional uint32 = 12
     *
     * @var int
     */
    protected $n_val = null;

    /**
     * type optional bytes = 13
     *
     * @var \Protobuf\Stream
     */
    protected $type = null;

    /**
     * Check if 'bucket' has a value
     *
     * @return bool
     */
    public function hasBucket()
    {
        return $this->bucket !== null;
    }

    /**
     * Get 'bucket' value
     *
     * @return \Protobuf\Stream
     */
    public function getBucket()
    {
        return $this->bucket;
    }

    /**
     * Set 'bucket' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setBucket($value)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->bucket = $value;
    }

    /**
     * Check if 'key' has a value
     *
     * @return bool
     */
    public function hasKey()
    {
        return $this->key !== null;
    }

    /**
     * Get 'key' value
     *
     * @return \Protobuf\Stream
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Set 'key' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setKey($value)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->key = $value;
    }

    /**
     * Check if 'r' has a value
     *
     * @return bool
     */
    public function hasR()
    {
        return $this->r !== null;
    }

    /**
     * Get 'r' value
     *
     * @return int
     */
    public function getR()
    {
        return $this->r;
    }

    /**
     * Set 'r' value
     *
     * @param int $value
     */
    public function setR($value = null)
    {
        $this->r = $value;
    }

    /**
     * Check if 'pr' has a value
     *
     * @return bool
     */
    public function hasPr()
    {
        return $this->pr !== null;
    }

    /**
     * Get 'pr' value
     *
     * @return int
     */
    public function getPr()
    {
        return $this->pr;
    }

    /**
     * Set 'pr' value
     *
     * @param int $value
     */
    public function setPr($value = null)
    {
        $this->pr = $value;
    }

    /**
     * Check if 'basic_quorum' has a value
     *
     * @return bool
     */
    public function hasBasicQuorum()
    {
        return $this->basic_quorum !== null;
    }

    /**
     * Get 'basic_quorum' value
     *
     * @return bool
     */
    public function getBasicQuorum()
    {
        return $this->basic_quorum;
    }

    /**
     * Set 'basic_quorum' value
     *
     * @param bool $value
     */
    public function setBasicQuorum($value = null)
    {
        $this->basic_quorum = $value;
    }

    /**
     * Check if 'notfound_ok' has a value
     *
     * @return bool
     */
    public function hasNotfoundOk()
    {
        return $this->notfound_ok !== null;
    }

    /**
     * Get 'notfound_ok' value
     *
     * @return bool
     */
    public function getNotfoundOk()
    {
        return $this->notfound_ok;
    }

    /**
     * Set 'notfound_ok' value
     *
     * @param bool $value
     */
    public function setNotfoundOk($value = null)
    {
        $this->notfound_ok = $value;
    }

    /**
     * Check if 'if_modified' has a value
     *
     * @return bool
     */
    public function hasIfModified()
    {
        return $this->if_modified !== null;
    }

    /**
     * Get 'if_modified' value
     *
     * @return \Protobuf\Stream
     */
    public function getIfModified()
    {
        return $this->if_modified;
    }

    /**
     * Set 'if_modified' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setIfModified($value = null)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->if_modified = $value;
    }

    /**
     * Check if 'head' has a value
     *
     * @return bool
     */
    public function hasHead()
    {
        return $this->head !== null;
    }

    /**
     * Get 'head' value
     *
     * @return bool
     */
    public function getHead()
    {
        return $this->head;
    }

    /**
     * Set 'head' value
     *
     * @param bool $value
     */
    public function setHead($value = null)
    {
        $this->head = $value;
    }

    /**
     * Check if 'deletedvclock' has a value
     *
     * @return bool
     */
    public function hasDeletedvclock()
    {
        return $this->deletedvclock !== null;
    }

    /**
     * Get 'deletedvclock' value
     *
     * @return bool
     */
    public function getDeletedvclock()
    {
        return $this->deletedvclock;
    }

    /**
     * Set 'deletedvclock' value
     *
     * @param bool $value
     */
    public function setDeletedvclock($value = null)
    {
        $this->deletedvclock = $value;
    }

    /**
     * Check if 'timeout' has a value
     *
     * @return bool
     */
    public function hasTimeout()
    {
        return $this->timeout !== null;
    }

    /**
     * Get 'timeout' value
     *
     * @return int
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    /**
     * Set 'timeout' value
     *
     * @param int $value
     */
    public function setTimeout($value = null)
    {
        $this->timeout = $value;
    }

    /**
     * Check if 'sloppy_quorum' has a value
     *
     * @return bool
     */
    public function hasSloppyQuorum()
    {
        return $this->sloppy_quorum !== null;
    }

    /**
     * Get 'sloppy_quorum' value
     *
     * @return bool
     */
    public function getSloppyQuorum()
    {
        return $this->sloppy_quorum;
    }

    /**
     * Set 'sloppy_quorum' value
     *
     * @param bool $value
     */
    public function setSloppyQuorum($value = null)
    {
        $this->sloppy_quorum = $value;
    }

    /**
     * Check if 'n_val' has a value
     *
     * @return bool
     */
    public function hasNVal()
    {
        return $this->n_val !== null;
    }

    /**
     * Get 'n_val' value
     *
     * @return int
     */
    public function getNVal()
    {
        return $this->n_val;
    }

    /**
     * Set 'n_val' value
     *
     * @param int $value
     */
    public function setNVal($value = null)
    {
        $this->n_val = $value;
    }

    /**
     * Check if 'type' has a value
     *
     * @return bool
     */
    public function hasType()
    {
        return $this->type !== null;
    }

    /**
     * Get 'type' value
     *
     * @return \Protobuf\Stream
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set 'type' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setType($value = null)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->type = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        if ( ! isset($values['bucket'])) {
            throw new \InvalidArgumentException('Field "bucket" (tag 1) is required but has no value.');
        }

        if ( ! isset($values['key'])) {
            throw new \InvalidArgumentException('Field "key" (tag 2) is required but has no value.');
        }

        $message = new self();
        $values  = array_merge([
            'r' => null,
            'pr' => null,
            'basic_quorum' => null,
            'notfound_ok' => null,
            'if_modified' => null,
            'head' => null,
            'deletedvclock' => null,
            'timeout' => null,
            'sloppy_quorum' => null,
            'n_val' => null,
            'type' => null
        ], $values);

        $message->setBucket($values['bucket']);
        $message->setKey($values['key']);
        $message->setR($values['r']);
        $message->setPr($values['pr']);
        $message->setBasicQuorum($values['basic_quorum']);
        $message->setNotfoundOk($values['notfound_ok']);
        $message->setIfModified($values['if_modified']);
        $message->setHead($values['head']);
        $message->setDeletedvclock($values['deletedvclock']);
        $message->setTimeout($values['timeout']);
        $message->setSloppyQuorum($values['sloppy_quorum']);
        $message->setNVal($values['n_val']);
        $message->setType($values['type']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'RpbGetReq',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'bucket',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'key',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_REQUIRED()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'r',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'pr',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'basic_quorum',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 6,
                    'name' => 'notfound_ok',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 7,
                    'name' => 'if_modified',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 8,
                    'name' => 'head',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 9,
                    'name' => 'deletedvclock',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 10,
                    'name' => 'timeout',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 11,
                    'name' => 'sloppy_quorum',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 12,
                    'name' => 'n_val',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 13,
                    'name' => 'type',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->bucket === null) {
            throw new \UnexpectedValueException('Field "\\Riak\\Client\\ProtoBuf\\RpbGetReq#bucket" (tag 1) is required but has no value.');
        }

        if ($this->key === null) {
            throw new \UnexpectedValueException('Field "\\Riak\\Client\\ProtoBuf\\RpbGetReq#key" (tag 2) is required but has no value.');
        }

        if ($this->bucket !== null) {
            $writer->writeVarint($stream, 10);
            $writer->writeByteStream($stream, $this->bucket);
        }

        if ($this->key !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeByteStream($stream, $this->key);
        }

        if ($this->r !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->r);
        }

        if ($this->pr !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeVarint($stream, $this->pr);
        }

        if ($this->basic_quorum !== null) {
            $writer->writeVarint($stream, 40);
            $writer->writeBool($stream, $this->basic_quorum);
        }

        if ($this->notfound_ok !== null) {
            $writer->writeVarint($stream, 48);
            $writer->writeBool($stream, $this->notfound_ok);
        }

        if ($this->if_modified !== null) {
            $writer->writeVarint($stream, 58);
            $writer->writeByteStream($stream, $this->if_modified);
        }

        if ($this->head !== null) {
            $writer->writeVarint($stream, 64);
            $writer->writeBool($stream, $this->head);
        }

        if ($this->deletedvclock !== null) {
            $writer->writeVarint($stream, 72);
            $writer->writeBool($stream, $this->deletedvclock);
        }

        if ($this->timeout !== null) {
            $writer->writeVarint($stream, 80);
            $writer->writeVarint($stream, $this->timeout);
        }

        if ($this->sloppy_quorum !== null) {
            $writer->writeVarint($stream, 88);
            $writer->writeBool($stream, $this->sloppy_quorum);
        }

        if ($this->n_val !== null) {
            $writer->writeVarint($stream, 96);
            $writer->writeVarint($stream, $this->n_val);
        }

        if ($this->type !== null) {
            $writer->writeVarint($stream, 106);
            $writer->writeByteStream($stream, $this->type);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->bucket = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->key = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->r = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->pr = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->basic_quorum = $reader->readBool($stream);

                continue;
            }

            if ($tag === 6) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->notfound_ok = $reader->readBool($stream);

                continue;
            }

            if ($tag === 7) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->if_modified = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 8) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->head = $reader->readBool($stream);

                continue;
            }

            if ($tag === 9) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->deletedvclock = $reader->readBool($stream);

                continue;
            }

            if ($tag === 10) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->timeout = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 11) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->sloppy_quorum = $reader->readBool($stream);

                continue;
            }

            if ($tag === 12) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->n_val = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 13) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->type = $reader->readByteStream($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->bucket !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->bucket);
        }

        if ($this->key !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->key);
        }

        if ($this->r !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->r);
        }

        if ($this->pr !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->pr);
        }

        if ($this->basic_quorum !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->notfound_ok !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->if_modified !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->if_modified);
        }

        if ($this->head !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->deletedvclock !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->timeout !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->timeout);
        }

        if ($this->sloppy_quorum !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->n_val !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->n_val);
        }

        if ($this->type !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->type);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->bucket = null;
        $this->key = null;
        $this->r = null;
        $this->pr = null;
        $this->basic_quorum = null;
        $this->notfound_ok = null;
        $this->if_modified = null;
        $this->head = null;
        $this->deletedvclock = null;
        $this->timeout = null;
        $this->sloppy_quorum = null;
        $this->n_val = null;
        $this->type = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \Riak\Client\ProtoBuf\RpbGetReq) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->bucket = ($message->bucket !== null) ? $message->bucket : $this->bucket;
        $this->key = ($message->key !== null) ? $message->key : $this->key;
        $this->r = ($message->r !== null) ? $message->r : $this->r;
        $this->pr = ($message->pr !== null) ? $message->pr : $this->pr;
        $this->basic_quorum = ($message->basic_quorum !== null) ? $message->basic_quorum : $this->basic_quorum;
        $this->notfound_ok = ($message->notfound_ok !== null) ? $message->notfound_ok : $this->notfound_ok;
        $this->if_modified = ($message->if_modified !== null) ? $message->if_modified : $this->if_modified;
        $this->head = ($message->head !== null) ? $message->head : $this->head;
        $this->deletedvclock = ($message->deletedvclock !== null) ? $message->deletedvclock : $this->deletedvclock;
        $this->timeout = ($message->timeout !== null) ? $message->timeout : $this->timeout;
        $this->sloppy_quorum = ($message->sloppy_quorum !== null) ? $message->sloppy_quorum : $this->sloppy_quorum;
        $this->n_val = ($message->n_val !== null) ? $message->n_val : $this->n_val;
        $this->type = ($message->type !== null) ? $message->type : $this->type;
    }


}

