<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@// Source: riak.proto
//   Date: 2015-01-16 03:40:25


namespace Riak\Client\ProtoBuf {

    class RpbListKeysResp extends \DrSlump\Protobuf\Message
    {
        /** @var \DrSlump\Protobuf\Descriptor */
        protected static $__descriptor;
        /** @var \Closure[] */
        protected static $__extensions = array();

        public static function descriptor()
        {
            $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, '.RpbListKeysResp');

            // repeated bytes keys = 1
            $f = new \DrSlump\Protobuf\Field();
            $f->number = 1;
            $f->name   = "keys";
            $f->rule   = \DrSlump\Protobuf\Protobuf::RULE_REPEATED;
            $f->type   = \DrSlump\Protobuf\Protobuf::TYPE_BYTES;

            $descriptor->addField($f);

            // optional bool done = 2
            $f = new \DrSlump\Protobuf\Field();
            $f->number = 2;
            $f->name   = "done";
            $f->rule   = \DrSlump\Protobuf\Protobuf::RULE_OPTIONAL;
            $f->type   = \DrSlump\Protobuf\Protobuf::TYPE_BOOL;

            $descriptor->addField($f);

            foreach (self::$__extensions as $cb) {
                $descriptor->addField($cb(), true);
            }

            return $descriptor;
        }

        /**
         * Check if "keys" has a value
         *
         * @return boolean
         */
        public function hasKeys()
        {
            return isset($this->keys);
        }

        /**
         * Clear "keys" value
         */
        public function clearKeys()
        {
            unset($this->keys);
        }

        /**
         * Get "keys" value
         *
         * @return \PhpOption\Option of type string[]
         */
        public function getKeys($idx = null)
        {
            if (null == $idx || !array_key_exists($idx, $this->keys)) {
                return  \PhpOption\None::create();
            }

            return new \PhpOption\Some($this->keys[$idx]);
        }

        /**
         * Get "keys" list of values
         *
         * @return string[]
         */
        public function getKeysList()
        {
            return $this->keys;
        }

        /**
         * Set "keys" value
         *
         * @param string[] $value
         */
        public function setKeys($value)
        {
            return $this->keys = $value;
        }

        /**
         * Add a new element to "keys"
         *
         * @param string $value
         */
        public function addKeys($value)
        {
            $this->keys[] = $value;
        }

        /**
         * Check if "done" has a value
         *
         * @return boolean
         */
        public function hasDone()
        {
            return isset($this->done);
        }

        /**
         * Clear "done" value
         */
        public function clearDone()
        {
            unset($this->done);
        }

        /**
         * Get "done" value
         * @return \PhpOption\Option of type (boolean)
         *
         *
         */
        public function getDone()
        {
            return \PhpOption\Option::fromValue($this->done);
        }

        /**
         * Set "done" value
         *
         * @param boolean $value
         */
        public function setDone($value)
        {
            return $this->done = $value;
        }
    }
}
